SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE ANSWER;
TRUNCATE TABLE DATA_REQUEST;
TRUNCATE TABLE DATASET;
TRUNCATE TABLE DATASET_THEME;
TRUNCATE TABLE DOWNLOAD;
TRUNCATE TABLE NOTICE;
TRUNCATE TABLE QUESTION;
TRUNCATE TABLE RESOURCE;
TRUNCATE TABLE SCRAP;
TRUNCATE TABLE USERS;


SET REFERENTIAL_INTEGRITY TRUE;
